###

GET http://localhost/serviciogeneral/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjM2ODQ4MjEsImV4cCI6MTcyMzY4NTAwMX0.EchV-1g-eB-8_WLDVGuVf8APmVM4svBkj8MPR5IRVW8
###

GET http://localhost/serviciogeneral/5 HTTP/1.1

###

POST http://localhost/serviciogeneral HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjI3OTk2MzgsImV4cCI6MTcyMjc5OTY5OH0.JMseezhZrCchcKaRQkBrCZS4C9pUWHpg7LwB0humBEw
Content-Type: application/json

{
  "NombreServicio": "Lunes"
}

###

DELETE http://localhost/serviciogeneral/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjI3OTI0MDAsImV4cCI6MTcyMjc5MjQ2MH0.9C3xRHlrBFzX0jnCZPtGEvpQYwdPP5FJ-WxgFV2gWKo

###

PUT http://localhost/serviciogeneral/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjI3OTMyNTYsImV4cCI6MTcyMjc5MzMxNn0.JysXgQNT20181QmPMJ9KFXFnvDHNhMoZlkSWGUfsMCg
Content-Type: application/json

{
  "NombreServicio": "Mosica"
}
