###

GET http://localhost/usuario/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjM2ODMxODksImV4cCI6MTcyMzY4MzM2OX0.texFhakiCxXrcuF3CKPZZJ-uwiD2mSbICVyJrnhVQMk
###

GET http://localhost/usuario/10 HTTP/1.1

###

POST http://localhost/usuario HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "prueba_usuario",
    "Contrasenna": "1234567",
    "Email": "pruebausuario@example.com",
    "FechaRegistro": "2024-06-08T00:34:27.693Z"
  }

###

DELETE http://localhost/usuario/11 HTTP/1.1

###

PUT http://localhost/usuario/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjM2ODI4ODQsImV4cCI6MTcyMzY4MzA2NH0._28CBqvo4sRFW9w0E73M2w-zIjHa9jUXqa9gJDbroyU
Content-Type: application/json

{
    "NombreUsuario": "lisa_rey",
    "Contrasenna": "123456",
    "Email": "pruebausuario@example.com",
    "FechaRegistro": "2024-06-08T00:34:27.693Z",
    "Rol": "Nivel1",
    "Token": "-"
  }

###
POST http://localhost/usuario/autenticar HTTP/1.1
Content-Type: application/json

{
  "Email": "john.doe@example.com",
  "Contrasenna": "123456"
}

###
POST http://localhost/usuario/validartoken HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjM2ODE5OTgsImV4cCI6MTcyMzY4MjE3OH0.7BFjG-V3w1rrqGHiB8vbAIXMbE62NnjIjnh_OGhn-0w