###

GET http://localhost/usuario/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjI4Mjg0NTAsImV4cCI6MTcyMjgyODUxMH0.7XGbit7llVkl0IwYp1dfoB09hqmrrALSYfggPYMOcUg
###

GET http://localhost/usuario/10 HTTP/1.1

###

POST http://localhost/usuario HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "prueba_usuario",
    "Contrasenna": "1234567",
    "Email": "pruebausuario@example.com",
    "FechaRegistro": "2024-06-08T00:34:27.693Z"
  }

###

DELETE http://localhost/usuario/11 HTTP/1.1

###

PUT http://localhost/usuario/12 HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "prueba_usuario",
    "Contrasenna": "1234",
    "Email": "pruebausuario@example.com",
    "FechaRegistro": "2024-06-08T00:34:27.693Z"
  }

###
POST http://localhost/usuario/autenticar HTTP/1.1
Content-Type: application/json

{
  "Email": "john.doe@example.com",
  "Contrasenna": "123456"
}

###
POST http://localhost/usuario/validartoken HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IkVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJSb2wiOiJOaXZlbDAiLCJJZFVzdWFyaW8iOjF9LCJpYXQiOjE3MjI0Nzk4MzMsImV4cCI6MTcyMjQ3OTg5M30.13lRGIudCnTK4GmrEUqW7-SX49UfTGyahGZMJiEDsFU